### ISSUE TITLE
Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception:  System.InvalidOperationException: unknown error: Xrm is not defined

### ISSUE THREAD

**Issue by naveedmcp** [Microsoft/EasyRepro#187]
Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
System.InvalidOperationException: unknown error: Xrm is not defined
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.14393 x86_64)

**Comment by naveedmcp** [comment]
@TYLEROL

**Comment by naveedmcp** [comment]
After I updated all tools, still getting the same error;

Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
OpenQA.Selenium.WebDriverException: unknown error: Xrm is not defined
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.14393 x86_64)

**Comment by TYLEROL** [comment]
@naveedmcp - Thanks for raising this issue. Have you altered the **CreateAccount** default sample test at all? If not, could you please provide more of the stack trace from the error test?

I suspect this may be coming from the following line:

`                xrmBrowser.GuidedHelp.CloseGuidedHelp();`

You could try commenting that line out and see if your results change. If not, is the application getting 100% of the way through the login experience? The steps should be:

- Attempt to access org, get redirected to O365 Login Page
- Input username, then supply password
- Interact with the **Stay Sign In** dialog
- Wait for main Dynamics 365 page to load
- Resume test steps

If this is not helpful, then the full stack trace when the exception is thrown, plus a screenshot of the browser window at time of exception will be helpful for investigation. **Please make sure there is no PII in the screenshot of the browser window**

Thanks,
Tyler

**Comment by naveedmcp** [comment]
@TYLEROL Thanks for your reply. After commenting the line of code mentioned above, i am now getting the following error;
Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

At the time of the error, following is the screen state;
- Input username, then supply the password

Following is the complete stack trace;
Test Name:	WEBTestCreateNewAccount
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount
Test Source:	C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs : line 22
Test Outcome:	Failed
Test Duration:	0:00:16.0783748

Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Api.Navigation.<>c__DisplayClass3_0.<OpenSubArea>b__0(IWebDriver driver) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Api\Pages\Navigation.cs:line 87
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.Navigation.OpenSubArea(String area, String subArea, Int32 thinkTime) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Api\Pages\Navigation.cs:line 80
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount() in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs:line 29
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by naveedmcp** [comment]
@TYLEROL 

No. I didn't alter any code. 

This is the stack trace when i uncomment the line back;

Test Name:	WEBTestCreateNewAccount
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount
Test Source:	C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs : line 22
Test Outcome:	Failed
Test Duration:	0:00:12.7332615

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.ExecuteScript(String script, Object[] args)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ExecuteScript(IWebDriver driver, String script, Object[] args) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 114
   at Microsoft.Dynamics365.UIAutomation.Api.GuidedHelp.get_IsEnabled() in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Api\Pages\GuidedHelp.cs:line 31
   at Microsoft.Dynamics365.UIAutomation.Api.GuidedHelp.<CloseGuidedHelp>b__3_0(IWebDriver driver) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Api\Pages\GuidedHelp.cs:line 50
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.GuidedHelp.CloseGuidedHelp(Int32 thinkTime) in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Api\Pages\GuidedHelp.cs:line 46
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount() in C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs:line 26
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
OpenQA.Selenium.WebDriverException: unknown error: Xrm is not defined
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.14393 x86_64)


Following is the screen;

![image](https://user-images.githubusercontent.com/31393621/46354444-9e360080-c62c-11e8-9f9d-4561463c24db.png)

**Comment by TYLEROL** [comment]
Thanks @naveedmcp. Based on your latest screenshot, this issue is because the EasyRepro sample code uses our default login code. The default login code expects the standard Office 365 login window as opposed to a federated login page.

You can adjust this by calling an overloaded Login method that supports a _CustomLoginAction_. I'll get the ADFSLogin.cs sample added back to the latest branches, however if you look at the releases/v8.1 branch, this sample file should exist. I've included it below as well.

The password field on the ADFS login window uses a different element id compared to the Office 365 login page so the problem is the password is not being input as expected. The code eventually tries to move on but is unable to because you are not on a Dynamics 365 web page.

Please let us know if you have any additional questions on implementing this in your scenario.

```
[TestMethod]
        public void TestCustomLogin()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, CustomLoginAction);
            }
        }

        public void CustomLoginAction(LoginRedirectEventArgs args)
        {
            //Login Page details go here.  You will need to find out the id of the password field on the form as well as the submit button. 
            //You will also need to add a reference to the Selenium Webdriver to use the base driver. 

            //Example
            //--------------------------------------------------------------------------------------
            var d = args.Driver;
            d.FindElement(By.Id("passwordInput")).SendKeys(args.Password.ToUnsecureString());
            d.ClickWhenAvailable(By.Id("submitButton"), new TimeSpan(0, 0, 2));

            //Insert any additional code as required for the SSO scenario

            //Wait for CRM Page to load
            d.WaitUntilVisible(By.XPath(Elements.Xpath[Reference.Login.CrmMainPage])
                , new TimeSpan(0, 0, 60),
            e =>
            {
                e.WaitForPageToLoad();
                e.SwitchTo().Frame(0);
                e.WaitForPageToLoad();
            },
                f => { throw new Exception("Login page failed."); });
            //--------------------------------------------------------------------------------------
        }
```

Best Regards,
Tyler

**Comment by naveedmcp** [comment]
@TYLEROL Thanks for the code;
Getting following build error;

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	**The name 'By' does not exist in the current context**	Microsoft.Dynamics365.UIAutomation.Sample	C:\Project Work\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs	56	Active

**Comment by naveedmcp** [comment]
@TYLEROL it worked. please keep posted when you have the fix ready. i have to copy the same method to all tests or put it in the base class and inherit

**Comment by TYLEROL** [comment]
@naveedmcp - I just submitted and merged a PR with the beta/v9.0.2 branch.

This change adds a method called **ADFSLoginAction** to the **LoginDialog.cs** code the web client. You should be able to call this from any of the code files using the following:

`xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, xrmBrowser.LoginPage.ADFSLoginAction);`

We'll get something added in the future for the Unified Interface scenarios. If you have any problems with the latest change, please re-open this issue and add any details as appropriate.

Thanks,
Tyler

**Comment by TYLEROL** [comment]
@naveedmcp - I pushed one additional update this morning that adds similar functionality to the Unified Interface.

`xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, client.ADFSLoginAction);`

Note that if you make any changes to the ADFSLoginAction within LoginDialog.cs, you would also need to make the correlating change in WebClient.cs for the Unified Interface.

Thanks!
Tyler

**Comment by SindhujaElangovan** [comment]
Hello Tylerol,

Good Day.

I'm facing the same issue "System.InvalidOperationException: unknown error: Xrm is not defined" but in a different browser-Firefox.
I'm getting this error once after the username and password is entered automatically it gets stuck in the Stay Sign In dialog and it is not redirected to the CRM home page. 

![firefox page](https://user-images.githubusercontent.com/45093818/48620039-8fc95b80-e9c4-11e8-9004-697a96d1eb12.PNG)
![xrm is not defined](https://user-images.githubusercontent.com/45093818/48620040-9061f200-e9c4-11e8-8cd4-b95812233e67.PNG)

I tried with your fix code but after that I'm getting-"System.NullReferenceException: Object reference not set to an instance of an object. And this time it gets stuck in the password page itself by not entering the password

Firefox version - 63.0.3 (64 bit)
geckodriver - v0.23.0-win64

Hope you can help me to resolve this issue.Thank You

Regards,
Sindhuja

**Comment by SindhujaElangovan** [comment]
@TYLEROL

**Comment by asmaafayed** [comment]
Hello @TYLEROL 
 I am very new to EasyRepro and using the latest version but still getting the same error <<Xrm not found>>
I am using "Firefox" and ADFLogin 

xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, xrmBrowser.LoginPage.ADFSLoginAction); 
xrmBrowser.GuidedHelp.CloseGuidedHelp();

Here's the stack error 
Test Name:	WEBTestCreateNewAccount
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount
Test Source:	F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs : line 21
Test Outcome:	Failed
Test Duration:	0:00:16.0861886

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ExecuteScript(IWebDriver driver, String script, Object[] args) in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 118
   at Microsoft.Dynamics365.UIAutomation.Api.GuidedHelp.get_IsEnabled() in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Api\Pages\GuidedHelp.cs:line 33
   at Microsoft.Dynamics365.UIAutomation.Api.GuidedHelp.<CloseGuidedHelp>b__3_0(IWebDriver driver) in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Api\Pages\GuidedHelp.cs:line 58
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.GuidedHelp.CloseGuidedHelp(Int32 thinkTime) in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Api\Pages\GuidedHelp.cs:line 54
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount() in F:\MOJ\CRM_Automation\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs:line 28
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
OpenQA.Selenium.WebDriverException: ReferenceError: Xrm is not defined
Result StandardOutput:	
BrowserAutomation Information: 9000 : BrowserInitialized invoked.
BrowserAutomation Information: 9001 : BrowserInitialized completed.
BrowserAutomation Information: 10001 : Command Start: Login - Attempt 1/0
BrowserAutomation Information: 10002 : Command Stop: Login - 1 attempts - total execution time 4841.4539ms
BrowserAutomation Information: 10001 : Command Start: Close Guided Help - Attempt 1/0
BrowserAutomation Error: 10003 : Command Error: Close Guided Help - Attempt 1/0 - OpenQA.Selenium.WebDriverException - ReferenceError: Xrm is not defined
BrowserAutomation Information: 9000 : BrowserDisposing invoked.
BrowserAutomation Information: 9001 : BrowserDisposing completed.
