### ISSUE TITLE
xrmBrowser.ActivityFeed.AddTask() throws InvalidOperationException

### ISSUE THREAD

**Issue by sammcquistan** [Microsoft/EasyRepro#520]
This issue is very similar to issue #161 . I noticed it hasn't been solved and has been open for nearly a year, but no resolution has been posted. I am running into the same issue, and my code is structured similarly.

**What completes:**
-Subject is filled in
-Description is filled in
-Date under 'Due' is filled in.

**What does not complete:**
-Time under 'due'
-Priority does not change, regardless of whether the OptionSet declaration is set to Normal or not.

**My Code:**
xrmBrowser.ActivityFeed.AddTask("Test Task", "This is a test to add a task to the record", new DateTime(2020, 5, 5), new OptionSet() { Name = "quickCreateActivity4212controlId_scheduledend", Value = "0" });

Yes, the name value in the option set is "quickCreateActivity4212controlld_scheduledend", which is the same value that issue #161 had. Wondering what the status of this is, or if there is a workaround. Thanks!

**Comment by TYLEROL** [comment]
Thanks for raising this issue @sammcquistan . I'll take a look into this and let you know if I have any problems reproducing the issue reported.

If all goes well, I'll let you know once I've confirmed the problem and when a fix is available.

Warm Regards,
Tyler

**Comment by thathi** [comment]
Looks like the test in devlop branch is passing with no issues.  @sammcquistan which version of CRM are you using? 

[TestMethod]
        public void WEBTestAddTask()
        {
            if (!HasData) return;
            XrmTestBrowser.ActivityFeed.SelectTab(Api.Pages.ActivityFeed.Tab.Activities);
            **XrmTestBrowser.ActivityFeed.AddTask("Schedule an appointment", "Capture preliminary customer and product information.", DateTime.Now, new OptionSet { Name = "quickCreateActivity4212controlId_prioritycode_d", Value = "Normal" });**
            XrmTestBrowser.ThinkTime(4000); 
        }

**Comment by sammcquistan** [comment]
@thathi we are currently on version 1710 (9.1.0.5626).

**Comment by TYLEROL** [comment]
@sammcquistan - I was able to take a look at this today as well, and like @thathi , I did not experience any problems. Both the Time and Priority values were set as expected. I tested with both the Develop and current releases/v9.1 branch. My test CRM organization is running on build 9.1.0.5626 was well.

If this issue still exists, I will note that for my Chrome browser testing, I was using v75 of the Browser, and ChromeDriver v74. **Could you please validate which WebBrowser and ChromeDriver versions you are testing with**? 

Mine are included below:

**Session info: chrome=75.0.3770.100
Driver info: chromedriver=74.0.3729.6**

**Comment by sammcquistan** [comment]
Hi all,

Thanks for helping me look into this. @TYLEROL I am using Chrome 75.0.3770.100 and my chromedriver version is 74.0.0 (most up-to-date version according to NuGet). I am still having issues with this script and am still unable to add a task to my activity feed. I have attached a GIF to display the behavior I am experiencing.

![createtask](https://user-images.githubusercontent.com/49731029/60108188-d1c23900-972d-11e9-9b92-a549c742ac7e.gif)

It appears that EasyRepro is able to execute the script up until setting the priority, and then the element is unable to be found. After the text entry sits and flashes for roughly 15 seconds, the script fails and now I am receiving a NullReferenceException. Here is the code for the test case I am running:

xrmBrowser.LoginPage.Login(_xrmUri, userName, _password, LoginHelper.ADFSLoginAction);
xrmBrowser.GuidedHelp.CloseGuidedHelp();

xrmBrowser.ThinkTime(500);
xrmBrowser.Navigation.OpenSubArea("Sales", "Contacts");

xrmBrowser.ThinkTime(500);
xrmBrowser.Grid.SwitchView("All Contacts");

Random Range = new Random();

xrmBrowser.ThinkTime(500);
xrmBrowser.Grid.OpenRecord(Range.Next(0, 46));

xrmBrowser.ThinkTime(5000);
xrmBrowser.ActivityFeed.SelectTab(Api.Pages.ActivityFeed.Tab.Activities);
xrmBrowser.ActivityFeed.AddTask("Test Task", "This is a test to add a task to the record", DateTime.Now, 
          new OptionSet { Name = "quickCreateActivity4212controlId_prioritycode", Value = "Normal" });
xrmBrowser.ThinkTime(3000);


Finally, here is some of the code from dev tools:
![task code](https://user-images.githubusercontent.com/49731029/60109031-3d58d600-972f-11e9-8553-c21ef960b575.PNG)

Thanks in advance,
Sam

**Comment by TYLEROL** [comment]
Thanks again @sammcquistan for these additional details. Based on what you provided, I suspect the issue was a missing _d in the Name of the OptionSet you provided.

**I have checked in a change to the develop branch to alleviate this. Could you please try this again using the latest from develop? Please note some additonal details following this...**

The checked in change adjusts this test method to fall more in-line with prior expected EasyRepro inputs. Instead of providing the full element id, you should instead provide the schema name of the field. In the AddTask() method, we'll do the element id translation for you.

In addition to this, I have updated the WEBTestAddTask() example with another use case for setting a DateTime value of something other than DateTime.Now().

Please let me know if you still receive exceptions with the latest code in develop.

Warm Regards,
Tyler

**Comment by sammcquistan** [comment]
Hi @TYLEROL ,

Great news, these hotfixes worked great. I did have to comment out this line of code from ActivityFeed.cs in my own solution:
this.SetCalenderValue(Elements.ElementId[Reference.ActivityFeed.ActivityAddTaskDueTimeId], dueDate.ToShortTimeString());

When I used the latest dev branch I was noticing that I was receiving a different error this time related to setting the time and that the element was not being found by chromedriver. I commented out the line of code shown above and the test worked smoothly. I am not sure if this is an issue specific to our Dynamics solution or if it is something wider, but I am happy that we were able to get this functionality working.

Thanks for all the help!

Sam

**Comment by TYLEROL** [comment]
Hi @sammcquistan - Thanks for helping validate here. I am having some difficulties getting my environment configured correctly, but is it possible that your 'DateTime' field within the organization is only enabled to show **Date Only** and not both **Date and Time**?

I have pushed one more change via #592 which performs a check to see if the 'Time' field is present, and if so, attempt to set it. **Could you help me validate that this alleviates the previously observed exception in your last update?**

Warm Regards,
Tyler

**Comment by sammcquistan** [comment]
Hi @TYLEROL ,

I'm fairly certain our organization has DateTime set to show Date initially, but a user is able to select a Time after confirming a Date. I believe that is what is leading me to this error with the most recent push, where the test method is unable to find that Time field. The test method continues to search for the Time field but instead is unable to. After a bit of time, the test fails and I get an error that the element was unable to be clicked. I believe it is being found, but it is not interactable (as we can see when we try to interact with it). See GIF below:

![task time unable](https://user-images.githubusercontent.com/49731029/60191855-97729d80-97fa-11e9-9911-efd6dc0e38bc.gif)

I believe this is out-of-the-box behavior (?) because we haven't made any updates to the Task function. I'm wondering if this would work if we add a line of code that moves the focus to another element and then back to the Time field.

**Comment by kishkk84** [comment]
Hi @TYLEROL 
In my case it's not selecting the priority. After it enters the time and the cursor is in time field only and it waited for around 10 seconds and then got the below error:

System.InvalidOperationException: 'Field: prioritycode Does not exist'

Chrome Version: 75.0.3770.100
chromedriver : 75.0.3770.90

**Error Details:**
`System.InvalidOperationException
  HResult=0x80131509
  Message=Field: prioritycode Does not exist
  Source=Microsoft.Dynamics365.UIAutomation.Api
  StackTrace:
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.<>c__DisplayClass23_0.<SetValue>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.SetValue(OptionSet option)
   at Microsoft.Dynamics365.UIAutomation.Api.Pages.ActivityFeed.<>c__DisplayClass10_0.<AddTask>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.Pages.ActivityFeed.AddTask(String subject, String description, DateTime dueDate, OptionSet priority, Int32 thinkTime)`

**Comment by tza3688gm** [comment]
P1729

**Comment by TYLEROL** [comment]
@kishkk84 - I'll take a look at this as a part of issue #610 

@sammcquistan - The core of these changes will be made available in build 9.1.0.6210 and the latest releases/v9.1 branch. Similar to the other issue posted here, it appears there may be a timing problem that is not quite replicating on my side. I was able to test with both Date/Time and Date Only fields with no issue. From your last update, and the other one posted here - these appear to be timing "misses" when checking for certain elements. I'll take a deeper look as a part of #610 .
